name: Publish Docker image
on:
  push:
    paths:
      - .github/workflows/docker-build.yml
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: terraform-aws:latest
